# Generated by Django 6.0.1 on 2026-02-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('netID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='User gender, used for calculating BMR', max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='User age in years', null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='User height in centimeters', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='User weight in kilograms', max_digits=5, null=True)),
                ('goal', models.CharField(blank=True, choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain')], help_text='User fitness goal, e.g., fat loss or muscle gain', max_length=20, null=True)),
            ],
            options={
                'ordering': ['netID', 'name', 'lastName'],
            },
        ),
        migrations.CreateModel(
            name='DiningHall',
            fields=[
                ('Dining_Hall_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniqueHall')],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.PositiveIntegerField(default=0)),
                ('carbohydrates', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('dining_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='mealPlanning.dininghall')),
            ],
            options={
                'ordering': ['dining_hall', 'dish_name'],
                'unique_together': {('dish_name', 'dining_hall')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_protein', models.PositiveIntegerField(default=0)),
                ('total_carbohydrates', models.PositiveIntegerField(default=0)),
                ('total_fat', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('contain_dish', models.ManyToManyField(blank=True, to='mealPlanning.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealPlanning.userprofile')),
            ],
            options={
                'ordering': ['meal_id'],
            },
        ),
    ]
