# Generated by Django 6.0.1 on 2026-02-04 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningHall',
            fields=[
                ('Dining_Hall_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniqueHall')],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('Meal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.PositiveIntegerField(default=0)),
                ('carbohydrate', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('diningHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealPlanning.dininghall')),
            ],
            options={
                'ordering': ['diningHall', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('netID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meals', models.ManyToManyField(blank=True, related_name='users', to='mealPlanning.meal')),
            ],
            options={
                'ordering': ['netID', 'name', 'lastName'],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('name', 'diningHall'), name='uniqueMeal'),
        ),
    ]
