# Generated by Django 6.0.1 on 2026-02-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlanning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='contain_dish',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
