# Generated by Django 6.0.1 on 2026-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="category",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="meal",
            name="contain_dish",
        ),
        migrations.AddField(
            model_name="meal",
            name="contain_dish",
            field=models.CharField(blank=True),
        ),
    ]
