# Generated by Django 6.0.1 on 2026-02-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='netID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
