# Generated by Django 6.0.1 on 2026-02-20 22:19

from datetime import date, timedelta
from django.db import migrations


def add_sample_meals(apps, schema_editor):
    """Add a demo user and sample meals so the meals-per-day chart shows data on deploy."""
    UserProfile = apps.get_model("mealPlanning", "UserProfile")
    Meal = apps.get_model("mealPlanning", "Meal")

    if Meal.objects.exists():
        return  # Already have data; don't duplicate

    profile, _ = UserProfile.objects.get_or_create(
        netID="demo",
        defaults={"name": "Demo", "lastName": "User"},
    )

    # Spread meals over the last 7 days so the line chart shows variation (e.g. 1, 2, 1, 3, 2, 1, 2)
    today = date.today()
    counts_per_day = [1, 2, 1, 3, 2, 1, 2]
    for i, count in enumerate(counts_per_day):
        day = today - timedelta(days=6 - i)
        for _ in range(count):
            Meal.objects.create(
                user=profile,
                date=day,
                total_calories=400 + (i * 50),
                total_protein=25,
                total_carbohydrates=45,
                total_fat=12,
                category="Breakfast",
                contain_dish="",
            )


def remove_sample_meals(apps, schema_editor):
    """Remove demo user's meals (optional reverse)."""
    UserProfile = apps.get_model("mealPlanning", "UserProfile")
    Meal = apps.get_model("mealPlanning", "Meal")
    Meal.objects.filter(user_id="demo").delete()
    UserProfile.objects.filter(netID="demo").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0002_meal_category_remove_meal_contain_dish_and_more"),
    ]

    operations = [
        migrations.RunPython(add_sample_meals, remove_sample_meals),
    ]
