# Generated by Django 6.0.1 on 2026-02-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlanning', '0002_remove_meal_contain_dish_meal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='meal',
            name='contain_dish',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
