# Generated by Django 6.0.1 on 2026-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlanning', '0002_userprofile_id_alter_userprofile_netid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='contain_dish',
        ),
        migrations.AddField(
            model_name='meal',
            name='contain_dish',
            field=models.ManyToManyField(blank=True, to='mealPlanning.dish'),
        ),
    ]
