# Generated by Django 6.0.1 on 2026-02-20

from datetime import date, timedelta
from django.db import migrations


def ensure_demo_meals(apps, schema_editor):
    """
    Ensure the demo user has meals for the last 7 days so the line chart always shows data.
    Idempotent: only adds meals for dates that don't have enough.
    """
    UserProfile = apps.get_model("mealPlanning", "UserProfile")
    Meal = apps.get_model("mealPlanning", "Meal")

    profile, _ = UserProfile.objects.get_or_create(
        netID="demo",
        defaults={"name": "Demo", "lastName": "User"},
    )

    today = date.today()
    counts_per_day = [1, 2, 1, 3, 2, 1, 2]  # meals per day for a nice line shape
    for i, target_count in enumerate(counts_per_day):
        day = today - timedelta(days=6 - i)
        existing = Meal.objects.filter(user=profile, date=day).count()
        to_add = max(0, target_count - existing)
        for _ in range(to_add):
            Meal.objects.create(
                user=profile,
                date=day,
                total_calories=400 + (i * 50),
                total_protein=25,
                total_carbohydrates=45,
                total_fat=12,
                category="Breakfast",
                contain_dish="",
            )


def noop_reverse(apps, schema_editor):
    """Leave demo data in place on reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0003_add_sample_meals_for_chart"),
    ]

    operations = [
        migrations.RunPython(ensure_demo_meals, noop_reverse),
    ]
