# Generated by Django 6.0.1 on 2026-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlanning', '0003_remove_meal_contain_dish_meal_contain_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
