# Generated by Django 5.1.6 on 2026-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0004_alter_meal_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="ai_confidence",
            field=models.CharField(
                blank=True,
                default="",
                help_text='"high", "medium", "low", or ""',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="allergens",
            field=models.JSONField(
                blank=True, default=list, help_text='e.g. ["Gluten", "Milk", "Soy"]'
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="course",
            field=models.CharField(
                blank=True,
                default="",
                help_text='e.g. "Entrees", "Breads"',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="dietary_flags",
            field=models.JSONField(
                blank=True, default=list, help_text='e.g. ["Vegetarian", "Vegan"]'
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="fiber",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Grams of fiber per serving",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="last_seen",
            field=models.DateField(
                blank=True,
                help_text="Last date this dish appeared on the menu",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="meal_period",
            field=models.CharField(
                blank=True,
                default="",
                help_text='e.g. "Continental Breakfast", "Lunch", "Dinner"',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="nutrition_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text='"wger", "ai_generated", or "" (unknown)',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="serving_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Station name, e.g. "Baked Expectations"',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="sodium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Milligrams of sodium per serving",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="uiuc_item_id",
            field=models.IntegerField(
                blank=True, help_text="ItemID from UIUC Dining API", null=True
            ),
        ),
    ]
