# Generated by Django 5.1.6 on 2026-03-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0005_dish_ai_confidence_dish_allergens_dish_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="serving_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text='e.g. "1 piece (~170g)", "1 cup", "1 bowl (~300g)"',
                max_length=100,
            ),
        ),
    ]
