# Generated by Django 5.1.6 on 2026-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0006_dish_serving_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary"),
                    ("light", "Lightly Active"),
                    ("moderate", "Moderately Active"),
                    ("active", "Active"),
                    ("very_active", "Very Active"),
                ],
                help_text="Activity level for TDEE calculation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_cal_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily calorie target", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_carbs_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily carbohydrate target (grams)", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_fat_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily fat target (grams)", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_protein_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily protein target (grams)", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="goals_source",
            field=models.CharField(
                blank=True,
                choices=[("ai", "AI-Calculated"), ("custom", "Custom")],
                help_text="How daily goals were set",
                max_length=10,
                null=True,
            ),
        ),
    ]
