# Generated by Django 5.1.6 on 2026-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0007_userprofile_activity_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="embedding",
            field=models.BinaryField(
                blank=True,
                help_text="Pickled numpy float32 array (384-dim) from all-MiniLM-L6-v2",
                null=True,
            ),
        ),
    ]
