# Generated by Django 5.1.6 on 2026-04-12 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0009_alter_dish_embedding_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecommendationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "context_signature",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("tip", models.TextField(blank=True, default="")),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_recommendation_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-generated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "snapshot_date"),
                        name="unique_daily_recommendation_snapshot",
                    )
                ],
            },
        ),
    ]
