# Generated by Django 5.1.6 on 2026-04-18 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0010_dailyrecommendationsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ai_chat_request", "AI chat request"),
                            ("follow_up_clicked", "Follow-up clicked"),
                            ("dish_added_from_ai", "Dish added from AI"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("prompt_chars", models.PositiveIntegerField(default=0)),
                (
                    "prompt_text_redacted",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "input_bucket",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-50", "0-50"),
                            ("51-150", "51-150"),
                            ("151-300", "151-300"),
                            ("301+", "301+"),
                        ],
                        db_index=True,
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "intent_label",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("error_type", models.CharField(blank=True, default="", max_length=64)),
                ("model_name", models.CharField(blank=True, default="", max_length=80)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("follow_up_clicked", models.BooleanField(default=False)),
                ("dish_added_from_ai", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="mealPlannin_event_t_422687_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="mealPlannin_user_id_caeb86_idx",
                    ),
                    models.Index(
                        fields=["event_type", "session_id"],
                        name="mealPlannin_event_t_bf5c75_idx",
                    ),
                ],
            },
        ),
    ]
