# Generated by Django 5.1.6 on 2026-04-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mealPlanning", "0011_aianalyticsevent"),
        ("mealPlanning", "0011_conversation_chatmessage_and_more"),
    ]

    operations = []
